### ISSUE TITLE
Make this a website

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/Maps4HTML.github.io#1]
Currently there's no overarching website for the CG on github, just repos for specs and components etc.  It would be ideal to have a home page that provides links to specs, resources, discussions, community etc.  

Currently this location simply redirects to the use cases document.

**Comment by AmeliaBR** [comment]
Thanks @prushforth — I was in the midst of writing up an issue to the same effect. Here's what I've got so far:

Tentative outline:

- Information about the community group, including links to
  * [the CG page & sign-up info on W3.org](https://www.w3.org/community/maps4html/)
  * [the public mailing list archive](https://lists.w3.org/Archives/Public/public-maps4html/)
  * maybe links to other accounts/forums for the groups ***Which ones are being actively used?***

- Links to draft specs (maybe two links each, one for the document and one for the repo)
  * [MapML spec](https://maps4html.github.io/MapML/spec/)
  * [HTML map element spec](https://maps4html.github.io/HTML-Map-Element/spec/)

- Links to other reports of the CG or related to CG work
  * [Maps for HTML Use cases & requirements](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/)
  * [Spatial Data on the Web Use Cases & Requirements](http://w3c.github.io/sdw/UseCases/SDWUseCasesAndRequirements.html)
  * The OGC testbed reports: [MapML Engineering Report from 2017](http://docs.opengeospatial.org/per/17-019.html) and @joanma747's testbed 14 report when it's available ***(anyone have a link that works?)***

- Links to the code repos & any relevant demos
  * [Web-map custom element](https://github.com/Maps4HTML/Web-Map-Custom-Element)
  * [MapML Leaflet plugin](https://github.com/Maps4HTML/MapML-Leaflet-Plugin)
  * [MapML server](https://github.com/Maps4HTML/MapMLServer)
  * ***Are these all still active/relevant? Any other code hosted elsewhere?***

- Links to relevant external specs and other projects
  * [GeoJSON](http://geojson.org/) / [RFC7946](https://tools.ietf.org/html/rfc7946)
  * [SVGMap (wiki in Japanese)](http://www.svgmap.org/wiki/index.php?title=%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8) and the [SVG Tiling and Layering Module proposal](https://www.w3.org/Submission/2011/SUBM-SVGTL-20110607/) / [SVG globalView proposal](https://www.w3.org/Graphics/SVG/WG/wiki/Proposals/globalView)
  * ***Any others?***

I can do the work, but I wanted to open a discussion so that established members of the group could make sure I'm including all the correct information!

**Comment by prushforth** [comment]
> maybe links to other accounts/forums for the groups Which ones are being actively used?

I have posted to discourse/web-mapping (currently down).

>- Links to draft specs (maybe two links each, one for the document and one for the repo)

>Are these all still active/relevant? Any other code hosted elsewhere?

There is code in our internal svn that should rightly get refactored for publication on github, including
the server stuff.  I would prefer to remove my employer's web template before publishing, among other tasks.  The server is definitely a work in progress, and has a few dependencies etc.  Maybe next time we chat I can give you a tour of that stuff and see what you think.  

>Spatial Data on the Web Use Cases & Requirements

meh.  I think the [best practices document](https://www.w3.org/TR/2017/NOTE-sdw-bp-20170928/) is ok though.  I have a "Best practice report" on my to-do list regarding MapML. 

> (anyone have a link that works?)

Apparently only the Testbed 13 stuff has been voted on for release.  Eventually the Testbed 14 documents will be available [here](http://docs.opengeospatial.org/per/)

> Links to the code repos & any relevant demos

There used to be a running demo of the custom element [here](https://www.webcomponents.org/element/Maps4HTML/Web-Map-Custom-Element
), but they upgraded something and the demo is temporarily out of order.  It does give you some instructions for installation of the component (based on bower), which are a bit outdated but still working, I believe.  Once the custom elements are re-written in native / no polyfill code, that site should work again, as I intend to publish that from npm.

We have got a MapML service available from [here](http://geogratis.gc.ca/mapml/) and CubeWerx has a MapML proxy for the Environment and Climate Change [GeoMet WMS here](http://geogratis.gc.ca/api/beta/mapml/static/cubewerx_cgdi_proxy_geomet_directory.html).  Also another [demo page from CubeWerx](http://geogratis.gc.ca/api/beta/mapml/static/cubewerx_cgdi_proxy_wmts.html) here.

> Links to relevant external specs and other projects
>  - Any others?

KML?  I think the globe that is often the backdrop for KML files is in scope, and so the KML content model may be relevant (it's similar to GeoJSON/ based of the same standard -> simple features).

WMS, WMTS are probably relevant standards to link to, since they form the backbone of the standard GeoWeb today.
